# .yarnrc.yml

# Specify the supported architectures for yarn
nodeLinker: node-modules

# Define the supported architectures for both macOS (darwin) and Linux (linux)
supportedArchitectures:
  - 'darwin-x64'
  - 'linux-x64'
